### ISSUE TITLE
通配符证书错误

### ISSUE THREAD

**Issue by MassSmith** [gfw-breaker/heroku-node-proxy#15]
在代理打开使用通配符证书时出现以下错误：

Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1058:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.EventEmitter.emit (domain.js:466:23)
    at TLSSocket._finishInit (_tls_wrap.js:636:8)

通过测试，发现使用通配符证书的网站，会出现这个错误，而一般的https证书则不会出现。
如：https://gb.falundafa.org 打开会出错，而https://www.minghui.org就不会出错。
这个错误如何改正？
我把node.js更新到了最新版也是这样，看来这是node.js库文件的问题。不知道有没有能力修复这个错误，或者禁止了这个错误，不再验证https证书的正确与否。

**Comment by MassSmith** [comment]
这个问题解决了，在nodejs中关闭证书的验证就可以了。
能不能互加一个联系方式？
如果你愿意，可以联系这个信箱，
53ekpf@moimoi.re
这是一次性邮件地址，有效期只有1个月，过后便会永久失效。

**Comment by MassSmith** [comment]
有关一个v2ray的问题，我想请教你，我发现v2ray会自己开启很多的udp端口。我现在对这个软件的安全性产生了疑问，但是又无法确定是否属实。
